### ISSUE TITLE
deprecated selectors :host and ::shadow

### ISSUE THREAD

**Issue by ghost** [mikedisbrow/codecademy-atom-syntax#1]
this "depreciation" issue lies in index.less, but I am not able to resolve it myself
Atom version is 1.14.3
your syntax version is 0.1.2
please help!

![screen shot 2017-02-18 at 23 18 38](https://cloud.githubusercontent.com/assets/13712320/23099603/dbf533fa-f630-11e6-8f98-adfa4fe08375.png)

**Comment by mikedisbrow** [comment]
Should be fixed now.

**Comment by ghost** [comment]
awesome - thanks for making this theme by the way!
